# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d16dd1d64494aba735af40239d6296c3629939e6c36bc1075ce592e2be71a151d49f15bf0429347c4b05d09e250f347ff541676d2f3ca21db9ae0b7cab9bf98

test:
  secret_key_base: 63e229c14b3af50855a3414ee124e296ecf1c0a06c4e36af37b153040e6ed021eeb28470efa5dee899eb97f432d7ec4ee3b69ba0ae4a5f60dc576eae89a515f6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
